# Generated by Django 5.2.8 on 2025-11-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_recommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
